{{- $config := .Values.config }}
{{- $pp := dict "Tendermint" (dict "PersistentPeers" (include "hsc.seeds" .)) }}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: {{ template "hsc.name" . }}
    chart: {{ template "hsc.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  name: {{ template "hsc.fullname" . }}-config
data:
  hsc.json: |-
{{ toJson (mergeOverwrite $config $pp) | indent 4 }}