{{- if .Values.contracts.enabled }}
{{- $refDir := printf "/ref" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hsc.fullname" $ }}-contracts
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ template "hsc.name" $ }}
    chart: {{ template "hsc.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: contracts-deploy
        image: {{ include "contracts.image" . | quote }}
        imagePullPolicy: {{ $.Values.contracts.image.pullPolicy }}
        volumeMounts:
        - mountPath: {{ $refDir }}
          name: ref-dir
        env:
        - name: CHAIN_URL_GRPC
          value: {{ template "hsc.fullname" $ }}-grpc:{{ .Values.config.RPC.GRPC.ListenPort }}
{{- include "settings" . | indent 8 }}
        command: ["/bin/sh", "-c", "{{ .Values.contracts.command }}"]
      restartPolicy: Never
      volumes:
      - name: ref-dir
        projected:
          sources:
            - configMap:
                name: {{ template "hsc.fullname" $ }}-config
            - configMap:
                name: {{ template "hsc.fullname" $ }}-genesis
  backoffLimit: 0
{{- end }}