apiVersion: v1
appVersion: 0.30.2
description: HiveSmartChain is a permissionable smart contract machine
home: https://github.com/hyperledger/hsc
icon: https://raw.githubusercontent.com/hyperledger/hsc/develop/docs/assets/images/hsc.png
keywords:
- blockchain
- smart contracts
- ethereum
- hyperledger
- evm
- web3
maintainers:
- email: casey@monax.io
  name: compleatang
- email: gregorydhill@outlook.com
  name: gregdhill
name: hsc
sources:
- https://github.com/hyperledger/hsc
version: 0.30.2
